### ISSUE TITLE
Multiple Sublime windows open causes ToDoReview to scan both projects.

### ISSUE THREAD

**Issue by augbog** [jonathandelgado/SublimeTodoReview#100]
I noticed if I had two separate Sublime Text windows open, each with their own project, ToDoReview will scan both projects. Is there a way to make it so that it only scans the window I ran the ToDoReview command from? (This may be out of a package's ability though). If this is not something worth being considered an issue, feel free to close.

**Comment by jonathandelgado** [comment]
I just tried this, but I was unable to replicate. The only thing that I noticed was shared between windows was the `X Files Scanned` in the status bar. Do you have some kind of plugin that would cause this behavior?

I'm on Windows 7 x64, ST3 Build 3065, how about you?

**Comment by augbog** [comment]
Ah apologies. The ToDoReview ended up printing the output on both my windows. I think I ended up running ToDoReview on a different project. Not sure if that in itself is an issue but it seems to be working fine after retesting it. 

I'm running Mac OS X Yosemite. Sorry about the false alarm! Closing.
