### ISSUE TITLE
Can't exlclude node_modules

### ISSUE THREAD

**Issue by toby1kenobi** [jonathandelgado/SublimeTodoReview#101]
I will apologise in advance, I feel this is likely to be a lack of understanding on my part, I've tried a lot of different things to get this to work though.

I'd like to exclude the contents of any node_modules folders, in any project. In ST2 I'm going to Preferences > Package Settings > ToDoReview > Settings - Default. Inm exclude_folders I'm trying all sorts of:

    	"*node_modules*",
    	"node_modules*",
    	"node_modules",
    	"**/node_modules/**"

(node_modules could appear at various depths in my projects' directory structures)

But I'm always seeing stuff from various node_modules folders in my review list - what am I doing wrong?

Thanks,

Toby

**Comment by jonathandelgado** [comment]
The following works for me.

```
{
	"exclude_folders": [
		"*.git*",
		"*node_modules*"
	]
}
```

**Comment by toby1kenobi** [comment]
And am I putting it in the right place (Settings - Default)? 

In case the extra detail helps, it's a CakePHP project where I'm using grunt for some build stuff, so node_modules isn't in the project root, it's at <root> - app - node_modules (and in various locations below that).

**Comment by jonathandelgado** [comment]
It should be in your TodoReview user settings, but default would work as long as you don't have user settings overwriting them.

**Comment by toby1kenobi** [comment]
Probably me, I just can't get this to work though.
