### ISSUE TITLE
Run TodoReview twice to switch windows

### ISSUE THREAD

**Issue by Poehli** [jonathandelgado/SublimeTodoReview#104]
First of all: Great addon!
I might have found a bug, though (step by step for reproduction):
1. open *.cpp file
2. add a TODO: as comment somewhere
3. pressed ctrl+shift+p
4. typeed TodoReview: Project and open Files
5. Enter pressed
=> it sais file was reparsed, but keeps the *.cpp file open, instead of switching to TodoReview
Would love to fix that myself, but I'm not much of a python coder ;)

**Comment by jonathandelgado** [comment]
I can't replicate this issue, are you using another package that might have caused this?

OS, Sublime version, Package version?

**Comment by Poehli** [comment]
I don't think that any of my other packages should mess with that (sublimeclang, clang format, package control and todoreview). 
Using an Ubuntu 14.04 fork (PinguyOS), Sublime 3 Build 3080, Package Version 3.0.6. 
I'll try disableing any package, let's see if that's related.

**Comment by Poehli** [comment]
Okay, it has something to do with my package sublimeclang, when installing it, this will issue will occur... strange

**Comment by jonathandelgado** [comment]
Just looked at the package, looks like it was deprecated. They are using some odd event monitors which is probably triggering this issue. Nothing much I can do about that, sorry.

**Comment by jonathandelgado** [comment]
@Poehli There was actually a brand new clang autocomplete package just added this morning, check out https://packagecontrol.io/packages/Clang-Complete
