### ISSUE TITLE
Prioritization

### ISSUE THREAD

**Issue by jnbn** [jonathandelgado/SublimeTodoReview#105]
I think it'd better to prioritize the tasks in reverse order (biggest comes first) or at least maybe there would be a configuration to make it reversible rather than using the default function.

**Comment by jonathandelgado** [comment]
Yeah, i'd accept a PR for that, just another config setting to flip the sort function.

**Comment by jonathandelgado** [comment]
Going to close for now as a non-issue, if you want to throw in a PR, just ref the issue.
