### ISSUE TITLE
Opening a todo always takes me to last item on list

### ISSUE THREAD

**Issue by sircharleswatson** [jonathandelgado/SublimeTodoReview#106]
I'm using ST3 on OSX. For some reason, when I press enter to take me to the todo item, it only opens the last item on the list. no matter which one I try to navigate to.

**Comment by jonathandelgado** [comment]
I can't replicate this, probably another plugin causing this?

**Comment by sircharleswatson** [comment]
maybe. How can I get you that information?

**Comment by jonathandelgado** [comment]
You just have to disable the other plugins manually and test, sublime doesn't have a safe mode, unfortunately.

In sublime, it's really easy for one badly programmed package to mess up random features; I'm pretty sure that is what is occurring here. For instance, just last week #104 had an issue with a clang package.

**Comment by jonathandelgado** [comment]
Closing as most likely caused by another package, reopen if you can reproduce with no other packages installed.
