### ISSUE TITLE
Allow multiple regexes in comment group

### ISSUE THREAD

**Issue by ErichDonGubler** [jonathandelgado/SublimeTodoReview#109]
There's certain cases with TODOs where I feel like the code itself is a sufficient remind of what I need to do. For instance, when I write the signature for a stream operator in C++:

```c++
friend std::ostream& operator<<(std::ostream& os, const MyClass& mc); //TODO
```

It feels a bit redundant -- perhaps even undesirable -- to add a comment to this. Just by looking at the signature of the unimplemented function I know what needs to be done. My suggestion is to simply let an array of regex strings be valid in the configuration for comment groups, i.e.:

```json
{
	"patterns": {
		"TODO": ["(?P<todo>.*//\\.*)TODO\\s*$", "TODO[\\s]*:[\\s]*(?P<todo>.*)$"],
        }
}
```

**Comment by jonathandelgado** [comment]
If you can manage to make this happen without rewriting the engine (because this would mess up a lot of stuff) I'll merge a PR. I'm not taking it on, though.

**Comment by ErichDonGubler** [comment]
I actually have implemented a solution that modifies some parts of the current source, but the changes aren't complicated. Expect a PR soon -- writing docs for my change.
