### ISSUE TITLE
Open Files Option displaying 0 results

### ISSUE THREAD

**Issue by corbanCloud** [jonathandelgado/SublimeTodoReview#111]
When I select "Open Files" no results are populated in the TodoReview file. Header is present with time stamp and files viewed etc. but no contents are present. Selecting "Project Files" works as expected, selecting "Project And Open Files" appears to only gather project files.

No errors in terminal.

Sublime Text 3 (Build 3083) Ubuntu 14.10

**Comment by corbanCloud** [comment]
Sorry had to close and reopen files. Probably a Sublime index thing? Closing issue.

**Comment by jonathandelgado** [comment]
Yeah, sounds odd. Sublime has some real funkyness with their API, glad you got it figured out though.
