### ISSUE TITLE
Enhancement: Let TodoReview inherit project file/folder excludes

### ISSUE THREAD

**Issue by bmcminn** [jonathandelgado/SublimeTodoReview#112]
Similar to #101, however I think it's wierd that I use `TodoReview: Project Files` and it doesn't utilize my `*.sublime-project` config.

---

Example `*.sublime-project` file:

```json
{
  "folders":
  [
    {
      "path": ".",
      "file_exclude_patterns": [
        "*.sublime-workspace",
        "LICENSE",
        "*.lock"
      ],
      "folder_exclude_patterns": [
        "vendor",
        "node_modules",
        "bower_components",
        ".grunt"
      ]
    }
  ]
}

```

**Comment by jonathandelgado** [comment]
This has been requested a few times, but sublime doesn't have an API for it; so there isn't really a good way to implement this, other than cloning the match system from a closed source project, which isn't something I'm interested in doing.
