### ISSUE TITLE
TODO review does not yield results.

### ISSUE THREAD

**Issue by jasonlav** [jonathandelgado/SublimeTodoReview#114]
Running Sublime Text Build 3083 on OS X 10.10.3.

Installed fresh version of Sublime with default preferences/settings. Installed package manager and than installed TodoReview. Created file with "//todo", "//TODO", "//@todo", "//@TODO", "#TODO", and "#todo" (each on a new line). Selected "TodoReview: Open Files" from the commands palette. Creates a new "TodoReview" file with the following copy:

`// Wednesday 05/06/15 at 03:52PM - 1 files in 0.0 secs`

No matter what I do (restarting, creating new files, etc), it never seems to yield any results.

**Comment by jonathandelgado** [comment]
There has to be a comment after `//todo` on each line
