### ISSUE TITLE
Feature req: Easy way of opening file containing the todo

### ISSUE THREAD

**Issue by flippingtables** [jonathandelgado/SublimeTodoReview#121]
For bookmarks, it would be great to be able to quickly jump to the place in a file where the TODO is.

Feature suggestion:
In the "TodoReview" view, highlight a Todo
click 'o' on your keyboard
ST then opens that file, and jumps directly to the line containing the Todo.

**Comment by jonathandelgado** [comment]
This is already a feature, just press the up and down arrows to select the todo and then press enter. Am I missing something?

**Comment by flippingtables** [comment]
Aha, well I'll be damned :+1: I was too quick on the trigger there :)
