### ISSUE TITLE
"TodoReview: Project Files" does not respect project "folder_exclude_patterns"

### ISSUE THREAD

**Issue by AndreTheHunter** [jonathandelgado/SublimeTodoReview#123]
When using "TodoReview: Project Files", it includes files in folders that have been excluded by "folder_exclude_patterns" in the project settings. These folders (and files) do not appear in the sidebar or search and so should not be included in TodoReview

**Comment by jonathandelgado** [comment]
This is mentioned in the readme and numerous other issues. Sublime does not offer a plugin API to see what files/folders are excluded, so you must configure TodoReview accordingly.
