### ISSUE TITLE
todoreview command does not exist

### ISSUE THREAD

**Issue by djahma** [jonathandelgado/SublimeTodoReview#124]
Hi, 
I just installed ToDoReview via packagecontrol, but when using the pallet to find the supposedly installed command "todoreview", nothing show up.
I restarted ST2, swapped a few projects and still no "todo review" command in the pallet.
So basically, I can't manage to use the plugin. Any idea what's wrong?

**Comment by jonathandelgado** [comment]
I would recommend disabling all other plugins to ensure you don't have some kind of collision.

Other than that, check console (ctrl+~) and let me know if you have any errors.

**Comment by djahma** [comment]
Thanks for the tip, I've disabled quite a few packages but the error remains. Console extract:
```
Reloading plugin /home/gman/.config/sublime-text-2/Packages/TodoReview/TodoReview.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./TodoReview.py", line 10, in <module>
    import io
  File ".\io.py", line 63, in <module>
ImportError: No module named _fileio
```
I don't know anything about python...

**Comment by jonathandelgado** [comment]
Looks like you have some environment issues. It's not able to import the standard `io` library.

I did a quick google and it looks like this is a problem with Ubuntu in particular. I would recommend you do the same and try some of the fixes. I don't know what else to tell you beyond that.

**Comment by djahma** [comment]
after googling for solutions, what solved the problem was the package manager fixing and updating its package. Indeed, after installing ST3, todoreview works fine. 
So the issue is with ToDoReview package on ST2. Good luck fixing it

**Comment by jonathandelgado** [comment]
@djahma Well ST2 is on Python 2.x while ST3 is on Python 3.x. It seems that the environment issue on Ubuntu only occurs in 2.x, so even though the upgrade fixed it, it isn't an issue with the package. :)

**Comment by djahma** [comment]
ok, well thanks for looking into it anyway, and your fast responses!

**Comment by sokolovs** [comment]
Replace
import io
to
import StringIO as io
in TodoReview.py
