### ISSUE TITLE
"include_paths" option does not appear to be working

### ISSUE THREAD

**Issue by RichardForrester** [jonathandelgado/SublimeTodoReview#125]
I set the include_paths option in Preferences->PackageSettings->TodoReview->Settings-User like so:

`{
    "include_paths": [
        "~/repos/app/app"
    ]
}`

or

`{
    "include_paths": [
        "~/repos/app/app",
        "~/repos/appl/database",
        "~/repos/app/tests",
        "~/repos/app/resources"
    ]
}`

When I ctrl+shift+p to **TodoReview: Project Files** nothing happens. When I remove the setting everything works as expected.

**Comment by jonathandelgado** [comment]
OS? Have you tried a real path instead of using `~`? You might be on an OS in which python doesn't know how to translate the shortcut.

**Comment by RichardForrester** [comment]
Ubuntu LTS 14.04  --sorry this is the first time I've ever opened an issue with anything (new programmer).

Your suggestion worked. I replaced "~" with "/home/{username}" and it works now. 

Thanks. If this type of issue isn't mentioned on the readme perhaps add a note.

Nice package!

**Comment by jonathandelgado** [comment]
Yeah, unfortunately there are way too many python oddities to note. Glad you got it all figured out.
