### ISSUE TITLE
Use mouse or go to line to select element in the list

### ISSUE THREAD

**Issue by crash5** [jonathandelgado/SublimeTodoReview#126]
Hi!

Is it possible to use the mouse or the go to line function to select an element from the todo list?

**Comment by jonathandelgado** [comment]
This has been discussed a lot. Not possible with SublimeText until they include a mouse API.

**Comment by crash5** [comment]
Ok. And the "goto line" method is possible?

**Comment by jonathandelgado** [comment]
If you can come up with a way to implement it, I would accept a PR.
