### ISSUE TITLE
NO list created

### ISSUE THREAD

**Issue by Tooblippe** [jonathandelgado/SublimeTodoReview#127]
HI,

I have created a project. Typed some text and added a couple of TODO, todo, ## todo, ## TODO tags but when I create the list there is nothing in the todo list.

What am I doing wrong?

(using ST3 on Mac)
Tobie

**Comment by jonathandelgado** [comment]
Not a lot of information to go on here...

Do these patterns match your regex?
Have you excluded any files or folders?
Errors in your console?

A full plugin config, a test file and console trace would be useful.
