### ISSUE TITLE
Pattern for Markdown tasks?

### ISSUE THREAD

**Issue by katrinleinweber** [jonathandelgado/SublimeTodoReview#128]
I have a the same problem as  #127 on Win7 64bit with [ST3 b3083](https://www.sublimetext.com/3)  but related to matching `[ ]` in Markdown, LaTeX and other files. My user setting keeps the default, and adds a new `Tasks` pattern:
```
{
	"patterns": {
		"TODO": "TODO[\\s]*?:[\\s]*(?P<todo>.*)$",
		"Task": "\\[\\s\\]"
	}
}
```
which works fine in any other RegEx tool I tested. I also tried `-\\s\\[\\s\\]` and `\\%\\s\\[\\s\\]`to specify `- [ ]` in .md and `% [ ]`in .tex but without success. TodoReview is searching through my files, but there is no console output and no results. Am I doing something wrong, or is TodoReview not recognising the escaped brackets?

**Comment by jonathandelgado** [comment]
Please read the readme regarding adding patterns. I have noted it's important to include a named group in the regex match.

Note the `<todo>` in your first pattern, but in your second pattern, there isn't even an unnamed capture.

**Comment by katrinleinweber** [comment]
Now I get it, thanks! I was confused about what "named group" referred to.
