### ISSUE TITLE
Crash on loading plugin

### ISSUE THREAD

**Issue by juanjorda** [jonathandelgado/SublimeTodoReview#132]
Sublime Text 2.0.2 running on Fedora Linux. Python 2.7.5
Plugin crashing on startup. On Sublime Console:

Reloading plugin /home/juanter/.config/sublime-text-2/Packages/TodoReview/TodoReview.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./TodoReview.py", line 12, in <module>
    import io
  File ".\io.py", line 63, in <module>
ImportError: No module named _fileio

I fixed the issue by commenting in TodoReview.py:

#import io

And replacing line 110: 
f = io.open(p, 'r', encoding=settings.get('encoding', 'utf-8'))
by 
f = open(p,'r')

Import io is not failing in python command line. Maybe is failing in the python interpreter embedded with Sublime? (sorry I do not know exactly how it works)

**Comment by jonathandelgado** [comment]
This looks like the same issue we had in #124, for some reason, ST2 is packaged with a different version of python on linux systems.

Thanks for the report.
