### ISSUE TITLE
Navigate and select without Vintage

### ISSUE THREAD

**Issue by RichardForrester** [jonathandelgado/SublimeTodoReview#138]
Thanks for the great package.

I've noticed that when ignoring the "Vintage" package there is no way to navigate the todo list or select a todo to go to the source. The arrow keys just navigate the cursor and enter just breaks the line. With "Vintage" active there's no problem. On OS X.

Is this by design? I thought from the documentation that I should be able to navigate the same as if I was in VIM mode but with the arrow keys.

**Comment by FichteFoll** [comment]
I have Vintage disabled and can move between todo entries using the j and k keys.

I intend to improve the experience in this regard, however.

**Comment by RichardForrester** [comment]
There must be something else going on that is different on my system because j and k just insert the letters "j" and "k" when I push them.

Sublime Text 3; OS X; installed via Package Control... idk, guess I'll just use Vintage. haha.

**Comment by RichardForrester** [comment]
I'm closing this issue. The problem appears to have something to do with a sequence of opening Sublime from the command line and then changing projects or something like that I haven't quite figured out. It does appear to be working property now after a restart.
