### ISSUE TITLE
Adding Dynamic Linking to File and Line Number

### ISSUE THREAD

**Issue by Xtremefaith** [jonathandelgado/SublimeTodoReview#139]
I'm curious how difficult would it be to make the report dynamically link to the TODO (or other), to their file and line number? Sublime's Find report does this pretty well and I have seen other packages do it so I'm curious if its an easy addition that would be a great feature to have :)

**Comment by FichteFoll** [comment]
This is currently tracked in #78 (which is a PR and probably why you didn't see it).
