### ISSUE TITLE
Show results on specific pattern only

### ISSUE THREAD

**Issue by UberGruber** [jonathandelgado/SublimeTodoReview#140]
Hey there!
Was wondering if it's possible to fetch only a specific pattern for the results, like "show me only the FIXME list" or "TODO and CHANGED only, please". 

If I'm not missing something, the only way I found to do this it's a custom edit in the `.sublime-project` file where you specify only the patterns you are interested in. Is there a more convenient way to achieve the same thing? 

Thanks a lot! :)

**Comment by jonathandelgado** [comment]
You are right, the only way to do this currently is editing the settings JSON.

**Comment by UberGruber** [comment]
Oh I see! Well tedius but at least effective
