### ISSUE TITLE
exclude_folders question (yet another)

### ISSUE THREAD

**Issue by CanRau** [jonathandelgado/SublimeTodoReview#141]
Sorry but I'm really not getting it

I have folder structure like ../htdocs/processwire/project/wire/core/Templates.php
I want all sub-/folders of /project/ to b searched and exclude the /wire/ folder completely

problem i nothing works
I tried
```
wire
*wire*
/wire/
wire/
wire*
```
the first one serves results but the mentioned Templates.php will be included even though it's within /wire/ folder
all other patterns won't show any match at all
from docs *wire* seems the way to go, I don't exactly know what the asterisks are for but for me it seems *wire* wire exclude /processwire/ too and that's the reason nothing matches at all

what am I doing wrong/missing?

would love to use your plugin :-)

ah, tried those settings in users todoreview settings

**Comment by beauCielBleu** [comment]
In the doc, it says: "This is a glob field, so make sure to add wildcards where needed.".
"Glob" for global path, I suppose(?), so maybe the reason you have to add the "*".

You can try:

```
"exclude_folders": [
		"*.git*",
		"\\wire\\"
	],
```
And tell me the result.

My settings look like this (if it can help you):
```
"exclude_folders": [
		"*.git*",
		"*Domaines*",
		"*Proprietes\\Depots*"
	],
```

**Comment by CanRau** [comment]
tried
"\\wire\\"
"*wire\\core*" to see what happens
but still no luck

**Comment by beauCielBleu** [comment]
Try to double the "\" ->"\\" (the exemple I gave you is exactly what is in my settings file).

**Comment by CanRau** [comment]
I'm sorry, maybe GH stripped the double backdashes because I didn't use code block..
So that's what I tried already
```
"\\wire\\"
"wire\\core"
```
test\\

**Comment by jonathandelgado** [comment]
@beauCielBleu  is correct. The setting is a glob, which means you can do things like `*node_modules/*/tests/*`.

For your example, `*/processwire/project/wire/*` would be the correct solution. Also, as pointed out in the thread, you need to escape your slashes in JSON. You can be as specific or lose with these globs as you want.

**Comment by CanRau** [comment]
So I can't just say in global settings that I never want the `/wire/` folder (nor subfolders) to be include

tried the following
```
"*\/Users\/admin\/htdocs\/proccesswire\/project\/wire\/*",
"\/Users\/admin\/htdocs\/proccesswire\/project\/wire\/",
"\/Users\/admin\/htdocs\/proccesswire\/project\/wire",
"\/Users\/admin\/htdocs\/proccesswire\/project\/wire*",
```
I'm on mac

aha, or will exclude_folder only work in project settings and not globally?

**Comment by beauCielBleu** [comment]
@CanRau Glad to hear that! ;]
