### ISSUE TITLE
Exclude folders but including some children

### ISSUE THREAD

**Issue by CanRau** [jonathandelgado/SublimeTodoReview#142]
Hi again,
really love TodoReview, it's a huge benefit to my workflow, thanks again for that!!

I would love to be able to exclude a folder but include some of its children
tried include_paths but it's not working exactly and actually I would love to be able to include folders glob style like exclude_folders because it's the same for all projects
so e.g.
```
"exclude_folders": [
    "*\/folder\/"
]
"include_folders": [
    "*\/folder\/child"
]
```
But maybe there is another way I'm not aware of?

**Comment by jonathandelgado** [comment]
Yeah, this is unfortunately not possible using the current engine. Will happily accept a PR.

The closest thing you can do today is exclude all children that you don't want.

**Comment by CanRau** [comment]
What a pitty but good to know thanks.
Unfortunately I'm not a Python developer, but hopefully someone else is interested in this possibility, too :D
