### ISSUE TITLE
Ubuntu and system's sftp

### ISSUE THREAD

**Issue by byaka** [jonathandelgado/SublimeTodoReview#147]
If file opened via ubuntu's sftp, it has path like `/run/user/1000/gvfs/sftp:host=path_to_file_on_server`.

Now if i press enter in todo preview, sublime try to open tab with path `/run/user/1000/gvfs/sftp` and ofcourse open empty file (with error in console `Unable to open /run/user/1000/gvfs/sftp`).

can this be fixed? or maybe not open a new tab, but focus existed tab with this file and only select specific line...

**Comment by jonathandelgado** [comment]
I'll be more than happy to accept a PR.
