### ISSUE TITLE
Language of days

### ISSUE THREAD

**Issue by rybarova** [jonathandelgado/SublimeTodoReview#149]
Hello I've your package for sublimetext3. 

Is there any way how I can set locale for days in settings? I've a set everything in my language (CZ) but only days are eng. 

Thank you for your time.

**Comment by jonathandelgado** [comment]
I used python's `datetime` library to generate those values. According to their documentation, they use the system locale to change both the format and language. [More information here](https://docs.python.org/2/library/datetime.html).

Possibilities:

- Your system isn't set to the correct language
- SublimeText isn't accurately grabbing your system language
- Python for some reason doesn't have translations for your language, so it defaults to English

**Comment by rybarova** [comment]
Thank you for fast reply. I dont know where is problem and how to fix it. Maybe is problem with, that my ST3 is portable version. I go test it.  Anyway thank you for your time.

**Comment by jonathandelgado** [comment]
Hey @rybarova, were you able to resolve this? Just checking old issues! :)

**Comment by rybarova** [comment]
My system have a set CZ language correctly. In other apps I have not problem with python translation.
I have same problem with normal version of ST, like with this portable version. So I dont know, why my SublimeText cant grabb this from my system. :( That is probably problem with sublime and not with your modul.
