### ISSUE TITLE
Add priorities to TODOs and then sort by them

### ISSUE THREAD

**Issue by dufferzafar** [jonathandelgado/SublimeTodoReview#153]
I was wondering what people use to add priorities to their todos.

For eg: If I had something like

```
# TODO: 0 - needs to be done asap
# TODO: 9 - will do it later
```

Can TodoReview sort the todos based on the numbers?

**Comment by dufferzafar** [comment]
There should also be a way to reorder the todos, so when you reorder lines in the TodoReview "view" - it should change the associated priorities.

I'll take a stab at this when I have some free time on my hands!

**Comment by dufferzafar** [comment]
And while we are at it, maybe a way to filter out todos?

Say only view todos containing "easy"!

**Comment by jonathandelgado** [comment]
Take a look at the readme for more information on how to sort by priorities (https://github.com/jonathandelgado/SublimeTodoReview#priorities).

I'd really prefer not to add the ability to reorder lines in the view. For something like that to persist it would have to edit the corresponding files and append a priority to the comment line. That can cause issues with files being changed in git when it was not intended for them to be modified, etc.

With filtering, usually what I do is use the tag syntax. If you need anything beyond that, I think it's best for you to just use the standard search. Sublime is pretty limiting when it comes to plugin UI implementation, so keep that in mind.
