### ISSUE TITLE
TodoReview does not exclude folders in `excluded_folders`, doesn't search project either.

### ISSUE THREAD

**Issue by steezeburger** [jonathandelgado/SublimeTodoReview#154]
I am _only_ seeing results from my `node_modules` directory.

Here is my config:
```
{
  "patterns": {
    "TODO": "TODO[\\s]*?:[\\s]*(?P<todo>.*)$",
    "NOTE": "NOTE[\\s]*?:[\\s]*(?P<note>.*)$",
    "FIXME": "FIX ?ME[\\s]*?:[\\s]*(?P<fixme>.*)$",
    "CHANGED": "CHANGED[\\s]*?:[\\s]*(?P<changed>.*)$"
  },
  "patterns_weight": {
  },
  "exclude_folders": [
    "*.git*",
    "node_modules"
  ],
  "exclude_files": [
    "*.sublime-workspace",
    "*.sublime-project"
  ],
  "case_sensitive": false,
  "render_include_folder": true,
  "render_folder_depth": 5,
  "render_maxspaces": 50,
  "render_header_format": "%d - %c files in %t secs",
  "render_header_date": "%A %m/%d/%y at %I:%M%p",
  "navigation_forward_skip": 10,
  "navigation_backward_skip": 10
}
```

**Comment by jonathandelgado** [comment]
Please read the readme section about excluding file and folders. https://github.com/jonathandelgado/SublimeTodoReview#excluding-files-and-folders

Your `exclude_folders` value for `node_modules` needs to be wrapped in stars to follow the glob format.

**Comment by steezeburger** [comment]
I did. You can see I excluded `node_modules` in my config that I pasted above. 

It seems using the pattern '**/node_modules/*' now has the package searching the right files, but the default Regex pattern for TODO did not pick anything up. 

I tried lots of different patterns, even a simple `TODO` and it did not work.
