### ISSUE TITLE
More Customization (for the report)

### ISSUE THREAD

**Issue by LordFokas** [jonathandelgado/SublimeTodoReview#157]
I've been using **TodoReview** for a while now and I'd like to start off by thanking you for the **amazing** job.
It has been really useful so far! :)

This being said, there are a few things I'd like to be able to do (and, well, Python isn't *really* my thing), most of them regarding how easily I can spot TODOs and tell them apart at a glance:

- ~~Ability to set the color for each declared pattern~~
- [ ] Ability to set number of blank lines between **pattern** groupings (I'd prefer 2 or 3 instead of 1)
- ~~Ability to set the color for the line number~~
- [ ] Ability to set the text of the separator ( currently ':' ) between the path and line number (and maybe its color)
- [ ] Space-padding the **TODO** number would be quite nice (Yes I'm one of those crazy obsessed devs, don't look at me like that). Maybe make that configurable in case not-quite-insane people like it as it is and don't mind paths not being aligned?
- ~~Ability to (buckle up this one is the worst yet) set the color of a path (or part of it) based on a regex expression. This is quite important for me because I automatically give each part of my tree different priorities independently of how critical the issue actually is. Giving colors to multiple parts of the same path would be quite cool (and useful for me) TBH.~~
- [ ] Insert a blank line between two consecutive **TODO**s in the list when their files' paths don't have a common ancestor more than **N** folders above. Currently I do this manually every time I generate a report.
- [ ] Ability to auto-save the generated report to a configurable path (like "*$project_root$/TodoReview.md*", which would be pushed in git and more or less readable on the web)

~~Of course, colors here would most likely be in the form of COMMENT / CLASS / FUNCTION / KEYWORD etc "constants", but if we could set them as a specific RGB value as well that'd be even nicer.~~

With this I don't mean to push you to implement all of the above, instead, this is a list of features that have some or a lot of value for me, and others might find the same as well.

*Also, in case you're not aware, I've made each thing a checkbox because it creates a progress bar on the issue list, and if a contributor clicks it will automagically update the issue to check it, which will update the progress bar on the issue and the milestone if any. GitHub is amazing* :)

**Comment by jonathandelgado** [comment]
- Setting the color for each pattern will never be possible just based on how sublime handles this stuff. We use a syntax to highlight, and those are static.
- The same constraint goes with other colors, they are entirely dependent on your current theme as mentioned in the readme. It was a pretty hacky solution to even get that working, but sublime is not meant for stuff like this.

Aside from those two mentions, the other requests you have are somewhat reasonable, but I feel like they take a lot of effort for just small improvements. I would be totally winning to accept a PR on them, if you want to give it a shot despite not knowing python. I just simply don't have the time now or in the foreseeable future to take any of them on.

**Comment by LordFokas** [comment]
I had a rough idea that doing anything that isn't straight up text editing would fall on the hackish side in Sublime...

I know colors are managed by themes, but can you not define what type (class, method, etc) something is to be colored as?

Even though I've been looking for an excuse to learn python for a few years now, I currently am too busy to take this on as well (and it looks like I have enough backlog for a few years).

**Comment by FichteFoll** [comment]
>I know colors are managed by themes, but can you not define what type (class, method, etc) something is to be colored as?

You can, but that is declared by the syntax definition, which is a static file.

Nothing prevents you from editing the syntax definition and adding custom patterns & scope assignments yourself, but this can't be done in a dynamic way.

**Comment by jonathandelgado** [comment]
Going to close this since it isn't really actionable.
