### ISSUE TITLE
Set default priority to 50

### ISSUE THREAD

**Issue by locomo** [jonathandelgado/SublimeTodoReview#158]
This is a feature request:

I've been enjoying using the priority feature but i'm finding that I want the ability to put items at the top of the list AND the bottom of the list.

With the default at 100 it forces me to assign a priority to every item. I'd rather not have to do this but only assign a priority to high and low priority items. If default was 50 we could explicitly set items to 1 (high priority) or 70 (low priority) .. without having to set a priority for most of the items that belong in the middle.

hope that makes sense!

**Comment by locomo** [comment]
i guess even better would be if its setting that can be customized

**Comment by jonathandelgado** [comment]
Yeah, actually that makes a ton of sense, I'm surprised no one has requested that before. I'll try to get this done this weekend, should be a one-liner.

**Comment by jonathandelgado** [comment]
Resolved in 4105649472382dd64b36f17590b4e0963434e86c and released in 3.0.12, thanks again!
