### ISSUE TITLE
It doesn't work at all

### ISSUE THREAD

**Issue by s-kaczmarek** [jonathandelgado/SublimeTodoReview#159]
Am I doing something wrong or is it just not working? My steps are presented in pictures
![screenshot from 2018-05-20 19-31-06](https://user-images.githubusercontent.com/12611162/40281625-9a151a86-5c64-11e8-9644-a88b318c3457.png)
![screenshot from 2018-05-20 19-31-24](https://user-images.githubusercontent.com/12611162/40281638-a1fd2112-5c64-11e8-8f34-400df51f624f.png)
![screenshot from 2018-05-20 19-31-35](https://user-images.githubusercontent.com/12611162/40281639-a406f690-5c64-11e8-89c0-a14af37aed10.png)

**Comment by jonathandelgado** [comment]
The default regex matches `// TODO: something`

**Comment by s-kaczmarek** [comment]
ok, I didn't noticed that I have to write ':' after 'TODO' Thank you so much!
