### ISSUE TITLE
Not working with Sublimetext 3?

### ISSUE THREAD

**Issue by zbeckman** [jonathandelgado/SublimeTodoReview#161]
Installed using package control and ran TodoReview on "Project and Open Files." It scans the files (about 50), taking 1.37 seconds, but the resulting report is empty (except for a header).

There are definitely `// TODO` style comments in the code.

**Comment by drone1** [comment]
Do you have a colon after TODO?

`    // TODO: <-- Don't forget the colon!`

I just installed last night and am on Submlime 3.1.1 and it's working, although excluding folders doesn't seem to be working as expected yet.
