### ISSUE TITLE
"exclude_folders" not working as expected

### ISSUE THREAD

**Issue by drone1** [jonathandelgado/SublimeTodoReview#162]
I realize this project is not in development anymore, but it would be very helpful you could tell me if there is something obviously wrong with my expectation that putting ".meteor" in "exclude_folders" would exclude all of .meteor from TodoReview: Project Files.

My .sublime-project file looks like the following, however, TodoReview ends up with results _within_ .meteor still.

`{
    "folders": [],
    "settings":
    {
			"todoreview": {
				"exclude_folders": [
					"*.git*",
					".meteor"
				]
			} 
    },
    "build_systems": []
}`

I've tried adjusting exclude_folders in TodoReview's Default and User settings, restarted, and nothing changes as far as I can tell – the package still finds results in folders like ".meteor/local/plugin-cache/ecmascript/0.10.5"

.meteor is in my project root folder, as is .sublime-project.

I'm using Sublime 3.1.1 and just installed the package last night. 

Great project btw – even searching open files has been really useful and cool. Thanks a lot!

**Comment by jonathandelgado** [comment]
You have to surround `.meteor` with stars, it's a glob pattern. `*.meteor*`.

**Comment by jonathandelgado** [comment]
To be completely honest with you, I haven't used sublime in a really long time, so my knowledge at this point is limited to what I have documented in this project's readme. According to that, it appears you are doing everything correctly for the project config. Looking at the code, it appears we get setting by looking in the project config under `todoreview`, if that is missing, we default to what we have for the user.

Try setting a random root setting in that project config, like your color scheme, and see if that persists. If it doesn't we can rule out that it is an issue with TodoReview. I'm relatively confident this code still works unless some of the new ST3 builds somehow broke their settings system.

**Comment by drone1** [comment]
Yep, good call.

So it seems my .sublime-project isn't doing anything:

```{
    "folders": [],
    "settings":
    {
        "font_size": 50,
        "tab_size": 50
    },
    "build_systems": []
}```

Restart Sublime, no huge voids for tabs or enormous font size. Will look elsewhere for a fix.

Thanks man!

By the way, what do you use instead of Sublime at this point?
