### ISSUE TITLE
Show context up to project root

### ISSUE THREAD

**Issue by dbeckwith** [jonathandelgado/SublimeTodoReview#165]
When working in a project, I like having the `render_include_folder` option, but having to set a constant `render_folder_depth` is a bit annoying, since the proper number to get full context might change from project to project. It would be great if this setting was a bit more dynamic, and would just render folders up to the project root. Right now I'm having to set `render_folder_depth` to `100`, which gives me paths up to my file system root and is *too much* context.

**Comment by jonathandelgado** [comment]
That sounds reasonable to me, I recall coding it that way because Sublime often did not give a project root (if it did at all?). I would be open to a PR on this if you would like to implement it.
