### ISSUE TITLE
Exclude python package imports

### ISSUE THREAD

**Issue by sammorley-short** [jonathandelgado/SublimeTodoReview#167]
Is it possible to prevent TodoReview from searching through all imported libraries? At the moment, when I run `TodoReview: Project Files`, it searches through all imported Python modules, which in my case is thousands of files, taking quite a while. :(

**Comment by FichteFoll** [comment]
Did you confire folder ignore patterns for this project? If yes, then #172 should cover this case (as a duplicate of this issue). If no, you should add your virtualenv (which I assume is what contains those imported libraries) to the exclude folders list. https://github.com/jonathanrdelgado/SublimeTodoReview#excluding-files-and-folders

**Comment by sammorley-short** [comment]
Yep, ignore patterns were configured in `.gitignore`, so #172 should address this, thanks.

Closing as duplicate of #172.
