### ISSUE TITLE
Feature Request: Command to only show TODOs for Open Files

### ISSUE THREAD

**Issue by wesbaker** [jonathandelgado/SublimeTodoReview#43]
Is there any way you could create a new command that only shows TODOs for open files?

**Comment by tomasdev** [comment]
@jonathandelgado I think it's not an edge case but an use case. Tell me why do you want to see project + open in the same list.
a) Considering open files are outside the project, probably I don't want them in the same todo list (different projects maybe?)
b) Considering open files are inside the project, then it has the same effect as "Current Project" in the command palette.

It seems more useful to have Current project as one option and Open files as a separate option.

**Comment by tomasdev** [comment]
I'm using the following Default.sublime-commands:
```
[
	{
		"caption": "TodoReview: Project Files",
		"command": "todo_review"
	},
	{
		"caption": "TodoReview: Open Files",
		"command": "todo_review",
		"args": { "open_files_only": true }
	}
]
```
