### ISSUE TITLE
SASS/SCSS support

### ISSUE THREAD

**Issue by PixelT** [jonathandelgado/SublimeTodoReview#84]
The patterns (e.g. TODO) doesn't work in *.scss files - they don't display on results list...

**Comment by LeonardoGentile** [comment]
I confirm, this won't work for file having `.sass` extensions. 

To reproduce: 
- I've commented all the personal user settings for the plugin
- I've create two empty files called `hello.css` and `hello.sass` within the same project folder
- I've added the exact same comment to both files: `// TODO: hello`  

RESULT:
the css TODO will be detected but the sass one won't
