### ISSUE TITLE
Support multiline TODOs

### ISSUE THREAD

**Issue by ddofborg** [jonathandelgado/SublimeTodoReview#86]
When I code I wrap all my TODOs as follows:

```
TODO: this is a long TODO
      which takes 2 lines
      actually 3.

TODO: one line TODO

TODO: another one line TODO
```

Unfortunately TodoReview sees only the first line of the multiline TODO. It would be great if it could take the other lines too.

**Comment by grahamannett** [comment]
Hey, saw this and was curious is this still closed to discussion?  I was looking at the engine and think its possible with some hard rules which no doubt wont work for everyone but if thats not possible would it be possible to create a way users could extend the extract() function to fit the multiline to their specs?  not sure how hard it would be but I could try it and PR if you arent totally adverse.  By the way, super great plugin! Im blown away by how useful it is

Would be dope if this could be to extendible with a few other things

**Comment by jonathandelgado** [comment]
@grahamannett I have a couple of problems with this feature:

- Language specific: when scanning todos, we need a way to determine if something else below it is also a comment. This might work for something like `//` where we know that the initial line had that prefix, but consider something like a comment block, we would need language specific rules to determine what constitutes another line in each language, which is something I really don't want to maintain.

- Performance: the way the current engine works, we get all the searched keys, concat them to a single regex and text each file, cleanly return those results. If we were to add an addition step where we also needed to compare each line underneath these regex matches, we would be potentially adding a lot of overhead, especially for users that have a significant amount of results. The overhead would come from doing additional regex matches to determine what prefix the initial matched comment had then searching from that.

- Display: the current navigation system would have to be completely overhauled for something like this to be implemented. We currently have a very simple and efficient layout and selection system. This is the least of my concerns, but it would be an annoying one to tackle.

With all of that being said, I am always open to PRs. This would without a doubt require a large rewrite of the engine and I would have to be pretty strict in the review to ensure the engine still works flawlessly and at the same level of performance. A lot of people rely on this plugin and I would hate to break something in that rewrite. I just want to be up-front with you before you start any work on this, it will undoubtedly take a ton of your time *(and accordingly mine to review it)*.

To specifically address your comment about the `extract` function being extended by the user, unless I am unaware of something newly added, I do not believe Sublime is capable of doing that at current. The only config options are through the standard JSON config. One could make the argument you could serialize a function then we could eval it in the plugin, but that is just prone to issues in my opinion.
