### ISSUE TITLE
Matches non-comments

### ISSUE THREAD

**Issue by niklas-r** [jonathandelgado/SublimeTodoReview#92]
Hello

This is my user config:
```json
{
    "case_sensitive": true,
    "patterns": {
        "TODO": "TODO[\\s]*?:[\\s]*(?P<todo>.*)$",
        "FIX": "FIX[\\s]*?:[\\s]*(?P<fix>.*)$",
        "NOTE": "NOTE[\\s]*?:[\\s]*(?P<note>.*)$",
        "CHANGED": "CHANGED[\\s]*?:[\\s]*(?P<changed>.*)$",
        "TEST": "TEST[\\s]*?:[\\s]*(?P<test>.*)$"
    },
    "exclude_folders": [
        "*.git*",
        "*node_modules*",
        "*lib*",
        "*vendor*",
        "*coverage*"
    ]
}
```

Some of the results:
```
## TEST (2)
1. environment/environment.js:33        'test',
2. environment/environment.js:34        'btest',
```

This refers to these lines:
```js
envs_= {
  LOCAL: 'local',
  STST:  'stst',
  ATST:  'atst',
  TEST:  'test',
  BTEST: 'btest',
  PROD:  'prod'
};
```

Is this expected behavior? Personally I'm only interested in results that are comments and where the first word match any of my patterns. Ex: `// TEST: write test for this` would match but anything not in a comment or even `// This should have a TEST` would not match. I thought that's how this plugin worked.

Do I have to add this to my patterns myself?

**Comment by jonathandelgado** [comment]
This is working as expected. This package is language neutral, meaning comments in any language can be matched, hence the reason why the comment prefix was left out of the regex.

As you suspect, this can be fixed by simply changing the regex to suit your personal needs.

**Comment by niklas-r** [comment]
Ok. Thank you for a quick answer :thumbsup:

**Comment by jonathandelgado** [comment]
@niklas-r No problem! `^(.*)\\/\\/\\s*TEST[\\s]*?:[\\s]*(?P<test>.*)$` should do it for you, by the way.
