### ISSUE TITLE
Access the default and user setting from the command pallette

### ISSUE THREAD

**Issue by rkpatel33** [jonathandelgado/SublimeTodoReview#95]
Is it possible to allow access to open the default and user settings from the command palette, just like you can the main sublime text setting?

**Comment by jonathandelgado** [comment]
This package follows the package control best practice for settings. You can get to this package settings by going to Preferences -> Package Settings -> TodoReview in your Menu Bar.

**Comment by rkpatel33** [comment]
Ok, thanks for the reply!
