### ISSUE TITLE
Feature: Add option for projects to open Todo list on startup

### ISSUE THREAD

**Issue by SacredSkull** [jonathandelgado/SublimeTodoReview#99]
Rather than assign a hotkey for the Todo list to open I'd personally prefer the option per project for the todo list to automatically open.

**Comment by ClementParis016** [comment]
:+1:

**Comment by jonathandelgado** [comment]
As long as it is off by default, I'd accept a PR.

**Comment by jonathandelgado** [comment]
Closing as non-issue, the PR is still welcome, of course.
